apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.conf.django_settings_module | quote }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.conf.superuser_username | quote  }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.conf.superuser_email | quote }}
  PAPERMERGE_DATABASE_TYPE: {{ .Values.conf.db_type | quote }}
  PAPERMERGE_DATABASE_USER: {{ .Values.conf.db_user | quote }}
  PAPERMERGE_DATABASE_NAME: {{ .Values.conf.db_name | quote }}
  PAPERMERGE_DATABASE_HOST: {{ .Values.conf.db_host | quote }}
{{- if .Values.conf.es.enabled -}}
  PAPERMERGE_ELASTICSEARCH_HOSTS: {{ .Values.conf.es.hosts | quote }}
  PAPERMERGE_ELASTICSEARCH_PORT: {{ .Values.conf.es.port | quote }}
{{- end}}
