{{- if .Values.ingress.enabled -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "backend"
  annotations:
    {}

spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingress.host }}`)
    services:
    - name: "backend"
      port: 80
{{- end}}