apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
data:
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.conf.superuser_password | b64enc | quote }}
  PAPERMERGE_SECRET_KEY: {{ .Values.conf.secret_key | b64enc | quote }}
  PAPERMERGE_DATABASE_PASSWORD: {{ .Values.conf.db_password | b64enc | quote }}
